---
title: "Presentations"
---

### 2019
**Patel K.F.**, Norris C.G., Bailey V.L., Zheng J., Bond-Lamberty B., Myers-Pigg A., Fansler, S.J., Rod, K.A. Soil carbon dynamics during a hysteretic drying-rewetting event. Poster at *American Geophysical Union Fall Meeting*. San Francisco, CA. 


**Patel K.F.**, Fernandez I.J., Gruselle M.C., Norton S.A., Nelson S.J., Weiskittel A. The Bear Brook Watershed in Maine: Three decades of chronic N enrichment and recovery. Poster at *American Geophysical Union Fall Meeting*. San Francisco, CA.

Norton S.A., Fernandez I.J., Nelson S.J., **Patel K.F.**. Trajectories of recovery from acid rain over 31 years (amnbient) and 2 years (experimental) at the Bear Brook Watershed in Maine. Presented at *Society of Freshwater Science Annual Meeting*. Salt Lake City, UT.  

### 2018

**Patel K.F.**, Fernandez I.J., Gruselle M., Norton S.A., Nelson, S.J. & Weiskittel A. Multi-decadal evolution of nitrogen dynamics at the Bear Brook Watershed in Maine. Poster presented at *North American Forest Soils Conference*. Quebec City, Canada. 

### 2017	

**Patel K.F.**, Tatariw C., Fernandez I.J., MacRae J.D. & Ohno T. Soil biogeochemistry in a changing climate: A snow removal experiment in Maine. Presented at *BIOGEOMON*. Litomyšl, Czech Republic. 

**Patel K.F.**, Tatariw C., Fernandez I.J., MacRae J.D. & Ohno T. Soil N response to a changing climate: A snow removal experiment in Maine. Presented at the *Northeastern Ecosystem Research Cooperative Meeting*. Saratoga Springs, NY. 

### 2016	

**Patel K.F.**, Tatariw C., Fernandez I.J., MacRae J.D. & Ohno T. Soil biogeochemistry in a changing climate: Effect of snow removal. Poster presented at the *American Geophysical Union Annual Meeting*. San Francisco, CA. 

**Patel K.F.**, Tatariw C., Fernandez I.J., MacRae J.D. & Ohno T. Soil biogeochemistry in a changing climate: Effect of snowpack loss. Poster presented at the *National Cooperative Soil Survey (Northeast Region) Annual Meeting*. Lake Placid, NY. 

**Patel K.F.**, Tatariw C., Fernandez I.J., MacRae J.D. & Ohno T. Nutrient dynamics in a changing climate: How does a decreasing snowpack influence soil biogeochemistry? Presented at the *Maine Sustainability and Water Conference*. Augusta, ME. 

### 2015	

**Patel K.F.**, Tatariw C., Fernandez I.J., MacRae J.D. & Ohno T. Effect of snow removal on soil biogeochemistry. Presented at the *ASA-CSSA-SSSA International Meetings*. Minneapolis, MN. 


Tatariw C., **Patel K.F.**, MacRae J.D, Fernandez I.J. & Simon K. The effect of snow removal on litter macroinvertebrate community composition. Poster presented at the *Entomological Society of America Annual Meeting*. Minneapolis, MN. 

**Patel K.F.** & Fernandez I.J. Is there a changing climatology at the Bear Brook Watershed in Maine? Poster presented at the *Northeastern Ecosystem Research Cooperative Meeting*. Saratoga Springs, NY. 

**Patel K.F.** & Fernandez I.J. Climatic Trends at the Bear Brook Watershed in Maine — Biogeochemistry of the vernal transition. Poster presented at the *Freshwater Science Symposium*. University of Maine, Orono, ME. 

### 2014	

**Patel K.F.** & Fernandez I.J. Climatic Trends at the Bear Brook Watershed in Maine — Biogeochemistry of the vernal transition. Poster presented at BIOGEOMON. Bayreuth, Germany. 

### 2013	

**Patel K.F.**, Scatena F.N. & Johnson A.H. Texture analysis of surface soils in the Luquillo mountains of northeastern Puerto Rico. Poster presented at the Geological Society of America — Southeastern Section Meeting. San Juan, PR. 
