---
layout: post
title: "Publications"
---

### 2024

Morris KA, Smith M, Bailey VL, Bittencourt-Peixoto R, Day DJ, Hamovit N, Hopple AM, Lee J, **Patel KF**, Regier P, Wilson SJ, Yarwood SA, Megonigal JP, Bond-Lamberty B. Methane flux from transplanted soil monoliths depends on moisture, but not origin. *Soil Biology and Biochemistry*. https://doi.org/10.1016/j.soilbio.2023.109296.


### 2023

Regier P, Ward ND, Izquierdo A, Baldwin AH, Day D, McElhinny J, **Patel KF**, Vargas R, Zheng J, EXCHANGE Consortium, Myers-Pigg A. Coastal inundation regime moderates the short-term effects of sediment and soil additions on seawater oxygen and greenhouse gas dynamics: a microcosm experiment. *Frontiers in Marine Science*. [https://doi.org/10.3389/fmars.2023.1308590]().

**Patel KF**, Myers-Pigg A, Bond‐Lamberty B, Barnes ME. nmrrr: A Reproducible Workflow for Binning and Visualizing NMR Spectra From Environmental Samples. *JGR Biogeosciences*. https://doi.org/10.1029/2023JG007768.

Morris KA, Bond‐Lamberty BP, Day DJ, **Patel KF**, Pennington SC, Ward ND, von Fischer JC. PoolDilutionR: An R package for easy optimization of isotope pool dilution calculations. *Methods in Ecology and Evolution*. https://doi.org/10.1111/2041-210X.14223.

Rooney EC, Bailey VL, **Patel KF**, Kholodov A, Golightly H, Lybrand RA. Topography and canopy cover influence soil organic carbon composition and distribution across a forested hillslope in the discontinuous permafrost zone. *Permafrost and Periglacial Processes*. https://doi.org/10.1002/ppp.2200.

Myers-Pigg A, Pennington SC, Homolka KK, Lewis AM, Otenburg O, **Patel KF**, Regier P, et al. Biogeochemistry of soils, sediments, and surface waters across the upland to wetland gradient of coastal interfaces. *Scientific Data*. https://doi.org/10.1038/s41597-023-02548-7.

**Patel KF**, Bond-Lamberty B, Jian J, Morris KA, McKever SA, Norris CG, Zheng J, Bailey VL. Carbon flux estimates are sensitive to data source: a comparison of field and lab temperature sensitivity data. *Environmental Research Letters*. https://doi.org/10.1088/1748-9326/ac9aca.


### 2022 

Rooney EC, Bailey VL, **Patel KF**, Possinger AR, Gallo AC, Bergmann M, SanClements M, Lybrand RA. The Impact of Freeze‐Thaw History on Soil Carbon Response to Experimental Freeze‐Thaw Cycles. *JGR Biogeosciences*. https://doi.org/10.1029/2022JG006889. 

Rooney EC, Bailey VL, **Patel KF**, Dragila M, Battu AK, Buchko AC, Gallo AC, Hatten J, Possinger AR, Qafoku O, Reno LR, SanClements M, Varga T, Lybrand RA. Soil pore network response to freeze-thaw cycles in permafrost aggregates. *Geoderma*. https://doi.org10.1016/j.geoderma.2021.115674.


### 2021

**Patel K.F.**, Smith A.P., Bond-Lamberty B., Fansler S.J., Tfaily M.M., Bramer L., Varga T., Bailey V.L. "Spatial access and resource limitations control carbon mineralization in soils". *Soil Biology and Biochemistry*. [doi:10.1016/j.soilbio.2021.108427](https://doi.org/10.1016/j.soilbio.2021.108427). *[VIEW PDF](https://github.com/kaizadp/kaizadp.github.io/blob/master/pdfs/Patel2021_SpatialAccess.pdf)*


**Patel K.F.**, Tatariw C., MacRae J.D., Ohno T., Nelson S.J., & Fernandez I.J. "Repeated freeze-thaw cycles increase extractable, but not total, carbon and nitrogen in a Maine coniferous soil". *Geoderma*. [doi:10.1016/j.geoderma.2021.115353](https://doi.org/10.1016/j.geoderma.2021.115353). *[VIEW PDF](https://github.com/kaizadp/kaizadp.github.io/blob/master/pdfs/Patel2021_freezethaw_incubation.pdf)*


Jian J., Steele M.K., Zhang L., Bailey V.L., Zheng J., **Patel K.F.**, Bond-Lamberty B. "On the use of air temperature and precipitation as surrogate predictors in soil respiration modelling". *European Journal of Soil Science*. [doi:10.1111/ejss.13149](https://doi.org/10.1111/ejss.13149)


Jian J., Bond-Lamberty B., Hao D., Sulman B.N., **Patel K.F.**, Zheng J., Dorheim K., Pennington S.C., Hartman M.D., Warner D., & Wieder W.R. "Leveraging observed soil heterotrophic respiration fluxes as a novel constraint on global-scale models". *Global Change Biology*. [doi:10.1111/gcb.15795](https://doi.org/10.1111/gcb.15795). 


**Patel K.F.**, Fansler S.J., Campbell T.P., Bond-Lamberty B., Smith A.P., RoyChowdhury T., McCue L.A., Varga T., & Bailey V.L. "Soil texture and environmental conditions influence the biogeochemical responses of soils to drought and flooding" *Communications Earth and Environment*. [doi:10.1038/s43247-021-00198-4](https://doi.org/10.1038/s43247-021-00198-4). *[VIEW PDF](https://github.com/kaizadp/kaizadp.github.io/blob/master/pdfs/Patel2021_3Soils_drought_flood.pdf)*


**Patel K.F.**, Fernandez I.J., Nelson S.J., Norton S.A., Spencer S.J. "The Bear Brook Watershed in Maine: Multi-decadal whole-watershed experimental acidification". *Hydrological Processes*. [doi:10.1002/hyp.14147](https://doi.org/10.1002/hyp.14147). *[VIEW PDF](https://github.com/kaizadp/kaizadp.github.io/blob/master/pdfs/Patel%202021.%20BBWM%20data%20note%20HyP.pdf)*


**Patel K.F.**, Myers-Pigg A., Bond-Lamberty B., Fansler S.J., Norris C.G., McKever S.A., Zheng J., Rod. K.A., & Bailey V.L. "Soil carbon dynamics during drying vs. rewetting: Importance of antecedent moisture conditions." *Soil Biology and Biochemistry*. [doi:10.1016/j.soilbio.2021.108165](https://doi.org/10.1016/j.soilbio.2021.108165). *[VIEW PDF](https://github.com/kaizadp/kaizadp.github.io/blob/master/pdfs/Patel%202021.%20Soil%20carbon%20hysteresis%20antecedent%20moisture.pdf)*


**Patel K.F.**, Tejnecky V., Ohno T., Bailey V.L., Sleighter R.L., & Hatcher P.G.. "Reactive oxygen species alter chemical composition and adsorptive fractionation of soil-derived organic matter." *Geoderma*. [doi:10.1016/j.geoderma.2020.114805](https://doi.org/10.1016/j.geoderma.2020.114805). *[VIEW PDF](https://github.com/kaizadp/kaizadp.github.io/blob/master/pdfs/Patel%202020.%20Fenton%20SOM%20adsorption.pdf)*


### 2020

Rod, K.A., **Patel K.F.**, Kumar S., Cantando E., Leng W., Kukkadapu R.K., Qafoku O., Bowden M., Kaplan D.I., & Kemner K.M. Dispersible colloid facilitated release of organic carbon from two contrasting riparian sediments. *Frontiers in Water* [doi: 10.3389/frwa.2020.560707](https://doi.org/10.3389/frwa.2020.560707)

**Patel K.F.**, Tatariw C., MacRae J.D., Ohno T., Nelson S.J., & Fernandez I.J. Snowmelt periods as hot moments for soil N dynamics: A case study in Maine, USA. *Environmental Monitoring and Assessment* [doi: 10.1007/s10661-020-08733-0](https://doi.org/10.1007/s10661-020-08733-0)

**Patel K.F.**, Fernandez I.J., Nelson S.J., Malcomb J., & Norton S.A. Contrasting stream nitrate and sulfate response to recovery from experimental watershed acidification. *Biogeochemistry* [doi: 10.1007/s10533-020-00711-5](https://doi.org/10.1007/s10533-020-00711-5)



### 2019	

Contosta, A.R., Casson, N.J., Garlick, S., Nelson, S.J., Ayres, M.P., Burakowski, E.A., Campbell, J., Creed, I., Eimers, C., Evans, C., Fernandez, I., Fuss, C., Huntington, T., **Patel, K.F.**, Sanders‐DeMott, R., Son, K., Templer, P., & Thornbrugh, C. Northern forest winters have lost cold, snowy conditions that are important for ecosystems and human communities. *Ecological Applications*. [doi: 10.1002/eap.1974](https://doi.org/10.1002/eap.1974).

Salvino, C.J., **Patel, K.F.**, Fernandez, I.J., Gruselle, M.-C., Tatariw, C., & MacRae, J.D. 2019. Phosphorus Limits Nitrogen Dynamics in the O Horizon of a Forested Watershed in Maine, USA. *Soil Science Society of America Journal*. [doi:10.2136/sssaj2019.02.0043](https://doi.org/10.2136/sssaj2019.02.0043).


**Patel, K.F.**, Fernandez, I.J., Nelson, S.J., Gruselle, M.-C., Norton, S.A., & Weiskittel, A.R. 2019. Forest N Dynamics after 25 years of Whole Watershed N Enrichment: The Bear Brook Watershed in Maine. *Soil Science Society of America Journal*. [doi:10.2136/sssaj2018.09.0348](https://doi.org/10.2136/sssaj2018.09.0348).


**Patel K.F.**, Jakubowski M.D., Fernandez I.J., Nelson S.J., & Gawley W. Soil nitrogen and mercury dynamics seven decades after a fire disturbance: A case study at Acadia National Park. *Soil, Water, & Air Pollution*. [doi: 10.1007/s11270-019-4085-1](https://doi.org/10.1007/s11270-019-4085-1).


### 2018		

**Patel K.F.** & Fernandez I.J. Long-term N mineralization in O horizon soils during 27 years of N enrichment at the Bear Brook Watershed in Maine, USA. *Environmental Monitoring and Assessment*. [doi: 10.1007/s10661-018-6945-3](https://doi.org/10.1007/s10661-018-6945-3).

**Patel K.F.**, Tatariw C., MacRae J.D., Ohno T., Nelson S.J., & Fernandez I.J. Soil C and N responses to snow removal and concrete frost in a coniferous Maine forest. *Canadian Journal of Soil Science*. [doi: 10.1139/CJSS-2017-0132](https://doi.org/10.1139/CJSS-2017-0132).

**Patel K.F.**, Nelson S.J., Spencer C.J., & Fernandez I.J. Fifteen-year record of soil temperature for the Bear Brook Watershed in Maine. *Scientific Data*. [doi: 10.1038/sdata.2018.153](https://doi.org/10.1038/sdata.2018.153).

### 2017

Tatariw C., **Patel K.F.**, Fernandez I.J., & MacRae J.D. The effect of snowpack loss on soil temperature and moisture. *Northeastern Naturalist*. [doi: 10.1656/045.024.s707](https://doi.org/10.1656/045.024.s707).

