---
output: html_document
runtime: shiny

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Soil Water Tension
***
## converting units



### {.tabset .tabset-fade .tabset-pills}

#### from pF

```{r, echo=FALSE}
library(shiny)

ui = (fluidPage(
  #titlePanel("Converting from pF"),
  sidebarLayout(position = "right",
    sidebarPanel(
      textInput("in_pf", "input pF", value = "0.66")
    ),
    
    mainPanel(
    #  h2("Converted Units"),
      h4("cm"),
      textOutput("out_cm"),
      h4("kPa"),
      textOutput("out_kpa")
    )
  )
))


server = function(input, output) {
  
  conv1 <- reactive({
    wtInput <- as.numeric(input$in_pf)
    wtInput
  })
  
  output$out_cm <- renderText({
    round(10^conv1(),2)
  })
  output$out_kpa <- renderText({
    round((10^conv1())/10,2)
  })
}

shinyApp(ui = ui, server = server)
```


#### from kPa

```{r, echo=FALSE}
library(shiny)

ui2 = (fluidPage(
  #titlePanel("Converting from pF"),
  sidebarLayout(position = "right",
    sidebarPanel(
      textInput("in_kpa", "input kPa", value = "100")
    ),
    
    mainPanel(
    #  h2("Converted Units"),
      h4("cm"),
      textOutput("out_cm2"),
      h4("pF"),
      textOutput("out_pf")
    )
  )
))


server2 = function(input, output) {
  
  conv1 <- reactive({
    wtInput <- as.numeric(input$in_kpa)
    wtInput
  })
  
  output$out_cm2 <- renderText({
    round(conv1()*10,2)
  })
  output$out_pf <- renderText({
    round(log10(conv1()*10),2)
  })
}

shinyApp(ui = ui2, server = server2)
```


#### calculations

pF = log<sub>10</sub>(suction as cm)

cm = kPa/10


### source
Kaizad F. Patel

https://github.com/kaizadp/shinyapps

