---
layout: post
title: "Publications"
---

### 2019	

Contosta, A.R., Casson, N.J., Garlick, S., Nelson, S.J., Ayres, M.P., Burakowski, E.A., Campbell, J., Creed, I., Eimers, C., Evans, C., Fernandez, I., Fuss, C., Huntington, T., **Patel, K.F.**, Sanders‐DeMott, R., Son, K., Templer, P., and Thornbrugh, C. Northern forest winters have lost cold, snowy conditions that are important for ecosystems and human communities. *Ecological Applications*. [doi: 10.1002/eap.1974](https://doi.org/10.1002/eap.1974).

Salvino, C.J., **Patel, K.F.**, Fernandez, I.J., Gruselle, M.-C., Tatariw, C., and MacRae, J.D. 2019. Phosphorus Limits Nitrogen Dynamics in the O Horizon of a Forested Watershed in Maine, USA. *Soil Science Society of America Journal*. [doi:10.2136/sssaj2019.02.0043](https://doi.org/10.2136/sssaj2019.02.0043).


**Patel, K.F.**, Fernandez, I.J., Nelson, S.J., Gruselle, M.-C., Norton, S.A., and Weiskittel, A.R. 2019. Forest N Dynamics after 25 years of Whole Watershed N Enrichment: The Bear Brook Watershed in Maine. *Soil Science Society of America Journal*. [doi:10.2136/sssaj2018.09.0348](https://doi.org/10.2136/sssaj2018.09.0348).


**Patel K.F.**, Jakubowski M.D., Fernandez I.J., Nelson S.J., Gawley W. Soil nitrogen and mercury dynamics seven decades after a fire disturbance: A case study at Acadia National Park. *Soil, Water, & Air Pollution*. [doi: 10.1007/s11270-019-4085-1](https://doi.org/10.1007/s11270-019-4085-1).


### 2018		

**Patel K.F.** & Fernandez I.J. Long-term N mineralization in O horizon soils during 27 years of N enrichment at the Bear Brook Watershed in Maine, USA. *Environmental Monitoring and Assessment*. [doi: 10.1007/s10661-018-6945-3](https://doi.org/10.1007/s10661-018-6945-3).

**Patel K.F.**, Tatariw C., MacRae J.D., Ohno T., Nelson S.J. & Fernandez I.J. Soil C and N responses to snow removal and concrete frost in a coniferous Maine forest. *Canadian Journal of Soil Science*. [doi: 10.1139/CJSS-2017-0132](https://doi.org/10.1139/CJSS-2017-0132).

**Patel K.F.**, Nelson S.J., Spencer C.J. & Fernandez I.J. Fifteen-year record of soil temperature for the Bear Brook Watershed in Maine. *Scientific Data*. [doi: 10.1038/sdata.2018.153](https://doi.org/10.1038/sdata.2018.153).

### 2017

Tatariw C., **Patel K.F.**, Fernandez I.J. & MacRae J.D. The effect of snowpack loss on soil temperature and moisture. *Northeastern Naturalist*. [doi: 10.1656/045.024.s707](https://doi.org/10.1656/045.024.s707).

